theme: jekyll-theme-slate
title: Well, Hello There!
description: This is a template homepage which you can use to host examples of your work. You can think of this as a digital portfolio for yourself.
